export const GET_CURRENT_WEATHER_REQUEST = 'GET_CURRENT_WEATHER_REQUEST';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_ERROR = 'GET_CURRENT_WEATHER_ERROR';

export const GET_DAILY_FORECAST_REQUEST = 'GET_DAILY_FORECAST_REQUEST';
export const GET_DAILY_FORECAST_SUCCESS = 'GET_DAILY_FORECAST_SUCCESS';
export const GET_DAILY_FORECAST_ERROR = 'GET_DAILY_FORECAST_ERROR';

export const GET_LOCATION_REQUEST = 'GET_LOCATION_REQUEST';
export const GET_LOCATION_SUCCESS = 'GET_LOCATION_SUCCESS';
export const GET_LOCATION_ERROR = 'GET_LOCATION_ERROR';
