# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: circleci/node:14

commands:
  install_dependencies:
    description: Install Dependencies
    steps:
      - run:
          name: Install Dependencies
          command: npm ci

jobs:
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - install_dependencies
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - persist_to_workspace:
          root: ~/
          paths:
            - ./repo

  linter:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Check Linter
          command: npm run lint && npm run prettier

  test:
    executor: default
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Run Test
          command: npm run test

workflows:
  version: 2
  integration:
    jobs:
      - build
      - linter:
          requires:
            - build
      - test:
          requires:
            - build
