import { ReactComponent as ComponentCloudyIcon } from '../../../../assets/images/weather/cloudy.svg';
import { ReactComponent as ComponentHazeIcon } from '../../../../assets/images/weather/haze.svg';
import { ReactComponent as ComponentHeavyRainIcon } from '../../../../assets/images/weather/heavy-rain.svg';
import { ReactComponent as ComponentPartlyCloudyIcon } from '../../../../assets/images/weather/partly-cloudy.svg';
import { ReactComponent as ComponentRainIcon } from '../../../../assets/images/weather/rain.svg';
import { ReactComponent as ComponentSleetIcon } from '../../../../assets/images/weather/sleet.svg';
import { ReactComponent as ComponentSnowIcon } from '../../../../assets/images/weather/snow.svg';
import { ReactComponent as ComponentSunnyIcon } from '../../../../assets/images/weather/sunny.svg';
import { ReactComponent as ComponentThunderstormIcon } from '../../../../assets/images/weather/thunderstorm.svg';
import { ReactComponent as ComponentHighIcon } from '../../../../assets/images/weather/high-icon.svg';
import { ReactComponent as ComponentHumidityIcon } from '../../../../assets/images/weather/humidity-icon.svg';
import { ReactComponent as ComponentLowIcon } from '../../../../assets/images/weather/low-icon.svg';
import { ReactComponent as ComponentPressureIcon } from '../../../../assets/images/weather/pressure-icon.svg';
import { ReactComponent as ComponentWindIcon } from '../../../../assets/images/weather/wind-icon.svg';
import { ReactComponent as ComponentSearchIcon } from '../../../../assets/images/search-icon.svg';

export const CloudyIcon = ComponentCloudyIcon;
export const HazeIcon = ComponentHazeIcon;
export const HeavyRainIcon = ComponentHeavyRainIcon;
export const PartlyCloudyIcon = ComponentPartlyCloudyIcon;
export const RainIcon = ComponentRainIcon;
export const SleetIcon = ComponentSleetIcon;
export const SnowIcon = ComponentSnowIcon;
export const SunnyIcon = ComponentSunnyIcon;
export const ThunderstormIcon = ComponentThunderstormIcon;
export const HighIcon = ComponentHighIcon;
export const HumidityIcon = ComponentHumidityIcon;
export const LowIcon = ComponentLowIcon;
export const PressureIcon = ComponentPressureIcon;
export const WindIcon = ComponentWindIcon;
export const SearchIcon = ComponentSearchIcon;
