import { ReactComponent as WCloudyIcon } from '../../../../../../assets/images/weather/cloudy.svg';
import { ReactComponent as WHazeIcon } from '../../../../../../assets/images/weather/haze.svg';
import { ReactComponent as WHeavyRainIcon } from '../../../../../../assets/images/weather/heavy-rain.svg';
import { ReactComponent as WPartlyCloudyIcon } from '../../../../../../assets/images/weather/partly-cloudy.svg';
import { ReactComponent as WRainIcon } from '../../../../../../assets/images/weather/rain.svg';
import { ReactComponent as WSleetIcon } from '../../../../../../assets/images/weather/sleet.svg';
import { ReactComponent as WSnowIcon } from '../../../../../../assets/images/weather/snow.svg';
import { ReactComponent as WSunnyIcon } from '../../../../../../assets/images/weather/sunny.svg';
import { ReactComponent as WThunderstormIcon } from '../../../../../../assets/images/weather/thunderstorm.svg';
import { ReactComponent as WHighIcon } from '../../../../../../assets/images/weather/high-icon.svg';
import { ReactComponent as WHumidityIcon } from '../../../../../../assets/images/weather/humidity-icon.svg';
import { ReactComponent as WLowIcon } from '../../../../../../assets/images/weather/low-icon.svg';
import { ReactComponent as WPressureIcon } from '../../../../../../assets/images/weather/pressure-icon.svg';
import { ReactComponent as WWindIcon } from '../../../../../../assets/images/weather/wind-icon.svg';

export const CloudyIcon = WCloudyIcon;
export const HazeIcon = WHazeIcon;
export const HeavyRainIcon = WHeavyRainIcon;
export const PartlyCloudyIcon = WPartlyCloudyIcon;
export const RainIcon = WRainIcon;
export const SleetIcon = WSleetIcon;
export const SnowIcon = WSnowIcon;
export const SunnyIcon = WSunnyIcon;
export const ThunderstormIcon = WThunderstormIcon;
export const HighIcon = WHighIcon;
export const HumidityIcon = WHumidityIcon;
export const LowIcon = WLowIcon;
export const PressureIcon = WPressureIcon;
export const WindIcon = WWindIcon;
